#!/usr/bin/env bash
# Configures nginx to run as the nginx user and listen on port 8080
useradd nginx
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80 default_server;/listen [::]:8080 default_server;/' /etc/nginx/sites-enabled/default
service nginx restart || /usr/sbin/nginx
