#!/usr/bin/env bash
# Configures a brand new Ubuntu machine with nginx and a custom
# X-Served-By header showing the server's hostname

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo -n "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

server_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    add_header X-Served-By \$hostname;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}"

echo "$server_config" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
