#!/usr/bin/env bash
# Installs and configures HAProxy on lb-01 to load balance
# between web-01 and web-02 using round-robin

# Install HAProxy
sudo apt-get update -y
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update -y
sudo apt-get install -y haproxy=2.8.\*

# Enable HAProxy to be managed via init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Backup existing config
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# HAProxy configuration
haproxy_config="
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    option  forwardfor
    option  http-server-close
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7080-web-01 44.203.140.27:80 check
    server 7080-web-02 3.90.3.141:80 check
"

echo "$haproxy_config" | sudo tee /etc/haproxy/haproxy.cfg

# Enable HAProxy on boot and restart
sudo systemctl enable haproxy
sudo service haproxy restart
