#!/usr/bin/env bash
# Installs nginx and configures it to listen on port 80 of all active IPv4 IPs
apt-get update
apt-get install -y nginx
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
